package com.mp.domain

enum Permission {

    CREATE_RECIPE('CREATE_RECIPE'),
    UPDATE_RECIPE('UPDATE_RECIPE'),
    DELETE_RECIPE('DELETE_RECIPE'),

    CREATE_SECURITY_ROLE('CREATE_SECURITY_ROLE'),
    READ_SECURITY_ROLE('READ_SECURITY_ROLE'),
    UPDATE_SECURITY_ROLE('UPDATE_SECURITY_ROLE'),
    DELETE_SECURITY_ROLE('DELETE_SECURITY_ROLE'),

    UPDATE_USER_ROLES('UPDATE_USER_ROLES'),
    LIST_USERS('LIST_USERS'),
    UPDATE_USERS('UPDATE_USERS'),
    DELETE_USERS('DELETE_USERS'),

    REMOVE_RECIPE_FROM_FAVOURITES('REMOVE_RECIPE_FROM_FAVOURITES'),
    REMOVE_RECIPE_ABUSE('REMOVE_RECIPE_ABUSE'),
    REMOVE_COMMENT_ABUSE('REMOVE_COMMENT_ABUSE')


    final String name

    Permission(String name) {
        this.name = name
    }

    public String toString() {
        return name
    }

}
